<?php

namespace backend\controllers;

use backend\models\StatisticReport;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends BaseController
{

    public function requiredAuthAction()
    {
        return [
            'index', 'logout'
        ]; // TODO: Change the autogenerated stub
    }

    public function unRequiredAuthAction()
    {
        return [
            'login'
        ]; // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => StatisticReport::find()
                ->innerJoin('banner', 'banner.id = statistic_report.banner_id')
                ->addSelect([
                    'banner.title',
                    'SUM(click) as click',
                    'SUM(shown) as shown',
                ])->groupBy('banner_id')
        ]);
        return $this->render('index.blade', [
            'dataProvider' => $dataProvider
        ]);
    }


    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'auth.blade';

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login.blade', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
}
